import type { Metadata } from 'next';
import { Domine, DM_Serif_Display, Special_Elite } from 'next/font/google';
import './globals.css';
import Header from './components/Header';

const domine = Special_Elite({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-domine',
});
const serifDisplay = DM_Serif_Display({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-serifDisplay',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${serifDisplay.variable} ${domine.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
